baseurl: ""

# Theme settings
doks:
    baseurl: "/15-440/fa2025/"
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: "15-440 Distributed Systems"
            image: true
        nav:
            - item_name: Syllabus
              item_url: '/syllabus'
            - item_name: Schedule
              item_url: '/schedule'
            - item_name: Office Hours
              item_url: '/officehours'
            - item_name: Assignments
              item_url: '/assignments'
            - item_name: Recitations
              item_url: '/recitations'
            - item_name: Past Exams
              item_url: '/past-exams'
            # - item_name: FAQ
            #   item_url: '/faq'
    footer:
        content:
            logo:
                text:
                image:
            copyright: Copyright &copy; 2025. Carnegie Mellon University <br>All rights reserved.
        social_list:
            # - network_name: facebook
            #   profile_url: '#'
            # - network_name: twitter
            #   profile_url: '#'
            # - network_name: instagram
            #   profile_url: '#'
            # - network_name: youtube
            #   profile_url: '#'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/


# Course logistics
course:
    semester: Fall 2025
    time: Tue/Thu 11:00-12:20 in CUC MCCNMY
    venue:
    edstem: &es 'https://edstem.org/us/courses/84244/discussion'
    gradescope: &gs 'https://www.gradescope.com/courses/1099007'
    pollev: &pe 'https://pollev.com/cmu15440'
    queuestatus:
        url: &qs 'https://ohq.eberly.cmu.edu/#/'
        name: '15-440 (Fall 2025)'
    canvas: 'https://canvas.cmu.edu/'
    project_timeline:
        proposal: 2020-04-22T23:59:00-07:00
        milestone1: 2020-05-08T23:59:00-07:00
        milestone2: 2020-05-22T23:59:00-07:00
        poster_and_report: 2020-06-12T23:59:00-07:00
        long_date_format: "%B %-d, %A %I:%M %p"
        syllabus_date_format: "%m/%d %A %I:%M %p"
    links:
        syllabus:
            icon:
            content: Syllabus
            url: '/syllabus'
            external_url: false
        past-projects:
            icon:
            content: Past Projects
            url: '/past-projects'
            external_url: false
        project-2018-win:
            icon:
            content: Winter 2018
            url: '/past-projects/#winter-2018'
            external_url: false
        project-2018-spr:
            icon:
            content: Spring 2018
            url: '/past-projects/#spring-2018'
            external_url: false
        project-2018-fall:
            icon:
            content: Fall 2018
            url: '/past-projects/#fall-2018'
            external_url: false
        project-2019-win:
            icon:
            content: Winter 2019
            url: '/past-projects/#winter-2019'
            external_url: false
        project-2019-spr:
            icon:
            content: Spring 2019
            url: '/past-projects/#spring-2019'
            external_url: false
        project-2019-fall:
            icon:
            content: Fall 2019
            url: '/past-projects/#fall-2019'
            external_url: false
        project-2020-win:
            icon:
            content: Winter 2020
            url: '/past-projects/#winter-2020'
            external_url: false
        video2018:
            icon:
            content: Lecture videos (Fall 2018)
            url: '/lecture/'
            external_url: false
        edstem:
            icon:
            content: Edstem
            url: *es 
            external_url: true
        pollev:
            icon:
            content: PollEv
            url: *pe
            external_url: true
        video:
            icon:
            content: Lecture videos (Canvas)
            url: 'https://canvas.stanford.edu/courses/117317/external_tools/5384'
            external_url: true
        queuestatus:
            icon:
            content: QueueStatus
            url: *qs
            external_url: true
        project_appt_calendly:
            content: Meet with Project TA
            url: '/officehours/#table'
            external_url: true
        gradescope:
            icon:
            content: Gradescope
            url: *gs
            external_url: true

    staff:
        - name: Heather Miller
          type: Instructor
          url: https://heather.miller.am
          image: heather.jpg
          email: heather.miller@cs.cmu.edu
        - name: Wenting Zheng
          type: Instructor
          url: https://wzheng.github.io/
          image: wenting.jpg
          email: wenting@cmu.edu
        - name: Elizabeth Gilbert
          email: evgilber@andrew.cmu.edu
          type: Head TA
          image: elizabethg.jpg          

    ta:
        - name: Aditri Gupta
          email: aditrig@andrew.cmu.edu
          type: TA
          image: aditrig.jpg
        - name: Alexa Lowe
          email: alexal@andrew.cmu.edu
          type: TA
          image: alexal.jpg
        - name: Andy Zhao
          email: ziyaoz@andrew.cmu.edu
          type: TA
          image: ziyaoz.jpg          
        - name: Daniel Zhang
          email: dzhang3@andrew.cmu.edu
          type: TA
          image: dzhang3.jpg
        - name: Gonzalo De Hermenegildo Sordo
          email: gdeherme@andrew.cmu.edu
          type: TA
          image: gdeherme.jpg
        - name: Gabriel Sha
          email: gsha@andrew.cmu.edu
          type: TA
          image: gsha.jpg
        - name: Lucy Wang
          email: lexinw@andrew.cmu.edu
          type: TA
          image: lexinw.jpg
        - name: Matthew Feraru
          email: mferaru@andrew.cmu.edu
          type: TA
          image: mferaru.jpg
        - name: May Paek
          email: mpaek@andrew.cmu.edu
          type: TA
          image: mpaek.jpg
        - name: Matthew Booth
          email: mwbooth@andrew.cmu.edu
          type: TA
          image: mwbooth.jpg
        - name: Maxwell Feng
          email: mzf@andrew.cmu.edu
          type: TA
          image: mzf.jpg
        - name: Nithya Arun
          email: nkarun@andrew.cmu.edu
          type: TA
          image: nkarun.jpg
        - name: Rhea Kripalani
          email: rkripala@andrew.cmu.edu
          type: TA
          image: rkripala.jpg
        - name: Stephen Chien
          email: shchien@andrew.cmu.edu
          type: TA
          image: shchien.jpg
        - name: Steven Shi
          email: sshi2@andrew.cmu.edu
          type: TA
          image: sshi2.jpg
        - name: Tianhao Gu
          email: tgu3@andrew.cmu.edu
          type: TA
          image: tgu3.jpg
        - name: Tanisha Mehta
          email: tsmehta@andrew.cmu.edu
          type: TA
          image: tsmehta.jpg
        - name: Varshini Subramanian
          email: varshins@andrew.cmu.edu
          type: TA
          image: varshins.jpg
        - name: Xinyu Li
          email: xinyul3@andrew.cmu.edu
          type: TA
          image: xinyul3.jpg





