baseurl: ""

# Theme settings
doks:
    baseurl: "/15-440/fa2022"
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: "15-440 Distributed Systems"
            image: true
        nav:
            - item_name: Syllabus
              item_url: '/syllabus'
            - item_name: Schedule
              item_url: '/schedule'
            - item_name: Office Hours
              item_url: '/officehours'
            - item_name: Assignments
              item_url: '/assignments'
            - item_name: Recitations
              item_url: '/recitations'
            - item_name: Past Exams
              item_url: '/past-exams'
            # - item_name: FAQ
            #   item_url: '/faq'
    footer:
        content:
            logo:
                text:
                image:
            copyright: Copyright &copy; 2020. - Carnegie Mellon University <br>All rights reserved.
        social_list:
            # - network_name: facebook
            #   profile_url: '#'
            # - network_name: twitter
            #   profile_url: '#'
            # - network_name: instagram
            #   profile_url: '#'
            # - network_name: youtube
            #   profile_url: '#'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/


# Course logistics
course:
    semester: Fall 2022
    time: <strong>Sec 1</strong> Tue/Thu 10:10-11:30  in GHC 4401<br><strong>Sec 2</strong> Tue/Thu 11:50-1:10 in DH 1212
    venue:
    piazza: &pz 'https://edstem.org/us/join/qdCuyz'
    gradescope: &gs 'https://www.gradescope.com/courses/390524'
    queuestatus:
        url: &qs 'https://cmu.ohqueue.com/#/'
        name: '15-440 (Fall 2022)'
    canvas: 'https://canvas.cmu.edu/'
    project_timeline:
        proposal: 2020-04-22T23:59:00-07:00
        milestone1: 2020-05-08T23:59:00-07:00
        milestone2: 2020-05-22T23:59:00-07:00
        poster_and_report: 2020-06-12T23:59:00-07:00
        long_date_format: "%B %-d, %A %I:%M %p"
        syllabus_date_format: "%m/%d %A %I:%M %p"
    links:
        syllabus:
            icon:
            content: Syllabus
            url: '/syllabus'
            external_url: false
        past-projects:
            icon:
            content: Past Projects
            url: '/past-projects'
            external_url: false
        project-2018-win:
            icon:
            content: Winter 2018
            url: '/past-projects/#winter-2018'
            external_url: false
        project-2018-spr:
            icon:
            content: Spring 2018
            url: '/past-projects/#spring-2018'
            external_url: false
        project-2018-fall:
            icon:
            content: Fall 2018
            url: '/past-projects/#fall-2018'
            external_url: false
        project-2019-win:
            icon:
            content: Winter 2019
            url: '/past-projects/#winter-2019'
            external_url: false
        project-2019-spr:
            icon:
            content: Spring 2019
            url: '/past-projects/#spring-2019'
            external_url: false
        project-2019-fall:
            icon:
            content: Fall 2019
            url: '/past-projects/#fall-2019'
            external_url: false
        project-2020-win:
            icon:
            content: Winter 2020
            url: '/past-projects/#winter-2020'
            external_url: false
        video2018:
            icon:
            content: Lecture videos (Fall 2018)
            url: '/lecture/'
            external_url: false
        piazza:
            icon:
            content: Edstem (like Piazza)
            url: *pz
            external_url: true
        video:
            icon:
            content: Lecture videos (Canvas)
            url: 'https://canvas.stanford.edu/courses/117317/external_tools/5384'
            external_url: true
        queuestatus:
            icon:
            content: QueueStatus
            url: *qs
            external_url: true
        project_appt_calendly:
            content: Meet with Project TA
            url: '/officehours/#table'
            external_url: true
        gradescope:
            icon:
            content: Gradescope
            url: *gs
            external_url: true

    staff:
        - name: Heather Miller
          type: Instructor
          url: https://heather.miller.am
          image: heather.jpg
          email: heather.miller@cs.cmu.edu
        - name: Peter Steenkiste
          type: Instructor
          url: https://www.cs.cmu.edu/~prs/
          image: peter.jpg
          email: prs@cs.cmu.edu
        - name: Wenting Zheng
          type: Instructor
          url: https://wzheng.github.io/
          image: wenting.jpg
          email: wenting@cmu.edu
        - name: Matthew Weidner
          email: maweidne@andrew.cmu.edu
          type: Head TA
          url: http://mattweidner.com/
          image: matthew.png
          email: maweidne@andrew.cmu.edu

    ta:
        - name: Boxuan Li
          email: boxuanli@andrew.cmu.edu
          type: TA
          image: boxuan-li.jpg
          # zoom_id: 9999999999
          # calendly: https://calendly.com/15440fall2020/firstname-lastname-oh
        - name: Chonghan Chen
          email: chonghac@andrew.cmu.edu
          type: TA
          image: silhouette.png
        - name: Edward Chen
          email: ejchen@andrew.cmu.edu
          type: TA
          image: edward-chen.jpg
        - name: Emily X Zhang
          email: exz@andrew.cmu.edu
          type: TA
          image: emily-zhang.png
        - name: Jinhao Zhu
          email: jinhaoz@andrew.cmu.edu
          type: TA
          image: jinhao-zhu.png          
        - name: Kanishka Bandaru
          email: kbandaru@andrew.cmu.edu
          type: TA
          image: kanishka-bandaru.jpg                    
        - name: Mingkang Li
          email: mingkanl@andrew.cmu.edu
          type: TA
          image: mingkang-li.jpg
        - name: Rohit Pandey
          email: rohitp@andrew.cmu.edu
          type: TA
          image: rohit-pandey.jpg
        - name: Shantanu Kamath
          email: shantank@andrew.cmu.edu
          type: TA
          image: shantanu-kamath.jpg          
        - name: Shuning Lin
          email: shuningl@andrew.cmu.edu
          type: TA
          image: shuning-lin.jpg
        - name: Sumanth Rao
          email: ssr2@andrew.cmu.edu
          type: TA
          image: sumanth-rao.jpg
        - name: Ying Chen
          email: yingc4@andrew.cmu.edu
          type: TA
          image: ying-chen.jpg
        - name: Yiwen (Victor) Song
          email: yiwenson@andrew.cmu.edu
          type: TA
          image: yiwen-song.jpg
        - name: Yizhou Sheng
          email: yizhoush@andrew.cmu.edu
          type: TA
          image: yizhou-sheng.jpg
        - name: Zeean Veljee
          email: zsv@andrew.cmu.edu 
          type: TA
          image: zeean-veljee.png



