# This is a basic workflow to help you get started with Actions

name: cd

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout
      uses: actions/checkout@v2

    # Install dependencies
    - name: dependencies
      uses: docker://ruby:2.5
      env:
        BUNDLE_PATH: .bundle
      with:
        entrypoint: bundle
        args: install -j=4

    # Build Jekyll site
    - name: build
      uses: docker://ruby:2.5
      env:
        BUNDLE_PATH: .bundle
        LANG: en_US.UTF-8
        LANGUAGE: en_US.UTF-8
        LC_ALL: C.UTF-8
      with:
        entrypoint: bundle
        args: exec rake build

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
